# Indexing, Selection and Filtering
Most real Pandas work is:

- selecting rows
- filtering data
- querying conditions

## Two Core Indexing Tools
Pandas provides two main indexers:
| Method   | Meaning                       |
| -------- | ----------------------------- |
| `loc[]`  | label-based access            |
| `iloc[]` | integer-position-based access |

In [1]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David"],
    "age": [21, 22, 23, 24],
    "gpa": [3.8, 3.4, 3.9, 3.2]
})

print(df)

      name  age  gpa
0    Alice   21  3.8
1      Bob   22  3.4
2  Charlie   23  3.9
3    David   24  3.2

In [2]:
df.iloc[0] # select first row

name    Alice
age        21
gpa       3.8
Name: 0, dtype: object

In [3]:
df.iloc[0,0] # select specific cell

'Alice'

In [4]:
df.iloc[0:2] # select multiple rows

    name  age  gpa
0  Alice   21  3.8
1    Bob   22  3.4

In [5]:
df.iloc[0:2,0:2]

    name  age
0  Alice   21
1    Bob   22

### loc — Label-Based Selection

In [6]:
df.loc[:,"name"]

0      Alice
1        Bob
2    Charlie
3      David
Name: name, dtype: object

In [7]:
df.loc[:,["name","gpa"]]

      name  gpa
0    Alice  3.8
1      Bob  3.4
2  Charlie  3.9
3    David  3.2

In [8]:
# Select rows by condition
df.loc[df["age"]>22]

      name  age  gpa
2  Charlie   23  3.9
3    David   24  3.2

### Boolean Filtering

In [9]:
df[df["age"]>21]

      name  age  gpa
1      Bob   22  3.4
2  Charlie   23  3.9
3    David   24  3.2

### Multiple Condition

In [10]:
# AND Condition
df[(df["age"] >21) & (df["gpa"]>3.5)]

      name  age  gpa
2  Charlie   23  3.9

Rules:
- use & not and
- wrap each condition in parentheses

**Python and does not work with Pandas Series**

In [12]:
# OR Condition
df[(df["age"] > 23) | (df["gpa"] > 3.8)]

      name  age  gpa
2  Charlie   23  3.9
3    David   24  3.2

### Filtering Text Data

In [13]:
df[df["name"]=="Alice"]

    name  age  gpa
0  Alice   21  3.8

In [14]:
df[df["name"] !="Bob"]

      name  age  gpa
0    Alice   21  3.8
2  Charlie   23  3.9
3    David   24  3.2

In [15]:
df[df["name"].isin(["Alice","Charlie"])]

      name  age  gpa
0    Alice   21  3.8
2  Charlie   23  3.9

### Filtering with NOT condition

In [16]:
df[~(df["age"] > 22)]

    name  age  gpa
0  Alice   21  3.8
1    Bob   22  3.4

### Resetting Index after Filtering

In [18]:
# After filtering
filtered = df[df["age"] > 21]
print(filtered)

      name  age  gpa
1      Bob   22  3.4
2  Charlie   23  3.9
3    David   24  3.2

In [20]:
filtered = filtered.reset_index(drop=True)
print(filtered)

      name  age  gpa
0      Bob   22  3.4
1  Charlie   23  3.9
2    David   24  3.2

| Pandas     | SQL                     |
| ---------- | ----------------------- |
| df[...]    | WHERE                   |
| loc        | SELECT columns + filter |
| conditions | WHERE clause            |

### Summary Table
| Operation           | Syntax                  |   |
| ------------------- | ----------------------- | - |
| First row           | `iloc[0]`               |   |
| Cell                | `iloc[row, col]`        |   |
| Column              | `loc[:, "col"]`         |   |
| Filter rows         | `df[df["col"] > value]` |   |
| Multiple conditions | `&` and `               | ` |
| Multiple values     | `isin()`                |   |